/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.*;
import Modelo.Candidato;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vleos
 */
public class GestionarCandidatos extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_candidato
     */
    RegistroEleccion objRegistroEleccion;
    DefaultComboBoxModel model;
    private DefaultTableModel model1;

    private final String[] COLUMNS = new String[]{
            "Nombre", "Apellido"
        };
    
    public GestionarCandidatos() {
        initComponents();
        
    }
    public GestionarCandidatos(RegistroEleccion objRegistroEleccion) {
        initComponents();
        
        this.objRegistroEleccion = objRegistroEleccion;
        moverEleccionesAComboBox();
        moverArregloATabla();
        fecha.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            moverArregloATabla();  
        }
    });
        
    }
    
     public void limpiarComboBox() {
        model = new DefaultComboBoxModel();
        this.fecha.setModel(model);
    }

    public void moverEleccionesAComboBox() {
        this.limpiarComboBox();
        String[] listafechas = this.objRegistroEleccion.getListaFecha();
       

        for (int i = 0; i < listafechas.length; i++) {
            
            model.addElement(listafechas[i]);
        }

    }
     public void limpiarTabla() {
        model1 = new DefaultTableModel();
        this.tblcandidatos.setModel(model1);

        for (String column : COLUMNS) {
           model1.addColumn(column); 
        }
    }

    public void moverArregloATabla() {
        this.limpiarTabla();
        int count = 0;
        if(this.fecha.getSelectedIndex()!= -1){
        Candidato[] listaCandidatos = this.objRegistroEleccion.getListaCandidatosDeVotacion(this.fecha.getSelectedIndex());
        if (listaCandidatos!= null){
        String[] fila = new String[COLUMNS.length];

            for (int i = 0; i < listaCandidatos.length; i++) {
                Candidato candidato = listaCandidatos[i];


                if (candidato != null) {  
                    fila[0] = candidato.getNombre();
                    fila[1] = candidato.getApellido();
                    count++;
                    model1.addRow(fila);
                    }
                }
            }
        
        }
    }

     public void ValidarFecha() {
        
        String[] listafechas = this.objRegistroEleccion.getListaFecha();
       

        for (int i = 0; i < listafechas.length; i++) {
            
           if(fecha.getSelectedItem().toString() == listafechas[i]){
               
               i = listafechas.length;
           }
          
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcandidatos = new javax.swing.JTable();
        buttonregistrarcandidato = new javax.swing.JButton();
        buttoncancelar = new javax.swing.JButton();
        fecha = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Candidatos");

        tblcandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblcandidatos);

        buttonregistrarcandidato.setText("Registrar candidato");
        buttonregistrarcandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonregistrarcandidatoActionPerformed(evt);
            }
        });

        buttoncancelar.setText("Cancelar");
        buttoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncancelarActionPerformed(evt);
            }
        });

        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de eleccion:");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonregistrarcandidato)
                                .addGap(12, 12, 12)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(12, 12, 12)
                                .addComponent(buttoncancelar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonregistrarcandidato)
                    .addComponent(buttoncancelar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonregistrarcandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonregistrarcandidatoActionPerformed
        int index = fecha.getSelectedIndex();
        RegistrarCandidatos rcand = new RegistrarCandidatos(objRegistroEleccion, index);
        rcand.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            moverArregloATabla();  // Actualiza la tabla
        }
    });
    
    rcand.setVisible(true);
        rcand.setVisible(true);
        
    }//GEN-LAST:event_buttonregistrarcandidatoActionPerformed

    private void buttoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttoncancelarActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int indiceEleccion = fecha.getSelectedIndex();
        int indiceCandidato = tblcandidatos.getSelectedRow();
        if (indiceCandidato >= 0) {
        if (objRegistroEleccion.BorrarIndiceCan(indiceEleccion, indiceCandidato)) {
            
            moverArregloATabla();
            JOptionPane.showMessageDialog(this, "Candidato eliminado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el candidato");
        }
    }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ModificarCandidato fmrmodificarcandidato = new ModificarCandidato(objRegistroEleccion,fecha.getSelectedIndex(),tblcandidatos.getSelectedRow(),this);
        fmrmodificarcandidato.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarCandidatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncancelar;
    private javax.swing.JButton buttonregistrarcandidato;
    private javax.swing.JComboBox<String> fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcandidatos;
    // End of variables declaration//GEN-END:variables
}
